apiVersion: v2
name: osbuilder
description: A Helm chart for osbuilder
appVersion: 0.6.0
version: 0.1.17
dependencies:
  - name: cert-manager
    version: v1.16.3
    alias: certManager
    repository: https://charts.jetstack.io
    condition: certManager.enabled
maintainers:
  - name: Plural
    email: support@plural.sh
home: https://github.com/pluralsh/osbuilder
type: application
